### ISSUE TITLE
Callback angir feil model

### ISSUE THREAD

**Issue by TrondBotnen** [Snarkdoof/transcribe#1]
Ved transcribe så avsluttes den med en callback hvor model oppgis. Den angis ikke samme modell som ble brukt til å starte rutinen. Se bilde:
![image](https://github.com/Snarkdoof/transcribe/assets/24937192/c0343773-2b4e-409b-9e39-bdf4327102a0)

Antar dette er løst ved å gjøre følgende endring: (se bilde)
![image](https://github.com/Snarkdoof/transcribe/assets/24937192/92d3d25b-d29d-434a-951d-1a1c6cc43905)

**Comment by Snarkdoof** [comment]
Thanks, fixed (in git).
